[package]
name = "rov-interface"
version = "0.1.0"
authors = ["geemili <minergeemili@gmail.com>"]

[dependencies]
serial = "0.3"
sdl2 = "0.25"
sdl2_ttf = "0.25"
fomat-macros = "0.1"
error-chain = "0.5"
vecmath = "0.2"
time = "0.1"
serial_enumerate = "0.1.0"
gilrs = "0.4.2"
